services:
  metadataservice:
    image: ghcr.io/metal-toolbox/hollow-metadaaservice:v0.0.32
    depends_on:
      crdb:
        condition: service_healthy
      metadataservice-migrate:
        condition: service_completed_successfully
    environment:
      - METADATASERVICE_OIDC_ENABLED=false
      - METADATASERVICE_CRDB_URI=postgresql://root@crdb:26257/defaultdb?sslmode=disable
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - metadataservice

  metadataservice-migrate:
    image: ghcr.io/metal-toolbox/hollow-metadataservice:v0.0.32
    command:
      migrate up
    depends_on:
      crdb:
        condition: service_healthy
    environment:
      - METADATASERVICE_CRDB_URI=postgresql://root@crdb:26257/defaultdb?sslmode=disable
    restart: on-failure
    networks:
      - metadataservice

  crdb:
    image: cockroachdb/cockroach:latest-v23.2
    volumes:
      - db:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - "8080:8080"
      - "26257:26257"
    restart: unless-stopped
    healthcheck:
      test: "curl http://localhost:8080/health?ready=1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - metadataservice

volumes:
  db:

networks:
  metadataservice:
