// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	InstanceIPAddresses string
	InstanceMetadata    string
	InstanceUserdata    string
}{
	InstanceIPAddresses: "instance_ip_addresses",
	InstanceMetadata:    "instance_metadata",
	InstanceUserdata:    "instance_userdata",
}
