// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

func testInstanceIPAddressesUpsert(t *testing.T) {
	t.Parallel()

	if len(instanceIPAddressAllColumns) == len(instanceIPAddressPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := InstanceIPAddress{}
	if err = randomize.Struct(seed, &o, instanceIPAddressDBTypes, true); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert InstanceIPAddress: %s", err)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, instanceIPAddressDBTypes, false, instanceIPAddressPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert InstanceIPAddress: %s", err)
	}

	count, err = InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testInstanceIPAddresses(t *testing.T) {
	t.Parallel()

	query := InstanceIPAddresses()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testInstanceIPAddressesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceIPAddressesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := InstanceIPAddresses().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceIPAddressesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InstanceIPAddressSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testInstanceIPAddressesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := InstanceIPAddressExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if InstanceIPAddress exists: %s", err)
	}
	if !e {
		t.Errorf("Expected InstanceIPAddressExists to return true, but got false.")
	}
}

func testInstanceIPAddressesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	instanceIPAddressFound, err := FindInstanceIPAddress(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if instanceIPAddressFound == nil {
		t.Error("want a record, got nil")
	}
}

func testInstanceIPAddressesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = InstanceIPAddresses().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testInstanceIPAddressesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := InstanceIPAddresses().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testInstanceIPAddressesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	instanceIPAddressOne := &InstanceIPAddress{}
	instanceIPAddressTwo := &InstanceIPAddress{}
	if err = randomize.Struct(seed, instanceIPAddressOne, instanceIPAddressDBTypes, false, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}
	if err = randomize.Struct(seed, instanceIPAddressTwo, instanceIPAddressDBTypes, false, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = instanceIPAddressOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = instanceIPAddressTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := InstanceIPAddresses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testInstanceIPAddressesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	instanceIPAddressOne := &InstanceIPAddress{}
	instanceIPAddressTwo := &InstanceIPAddress{}
	if err = randomize.Struct(seed, instanceIPAddressOne, instanceIPAddressDBTypes, false, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}
	if err = randomize.Struct(seed, instanceIPAddressTwo, instanceIPAddressDBTypes, false, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = instanceIPAddressOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = instanceIPAddressTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func instanceIPAddressBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func instanceIPAddressAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func instanceIPAddressAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func instanceIPAddressBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func instanceIPAddressAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func instanceIPAddressBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func instanceIPAddressAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func instanceIPAddressBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func instanceIPAddressAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *InstanceIPAddress) error {
	*o = InstanceIPAddress{}
	return nil
}

func testInstanceIPAddressesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &InstanceIPAddress{}
	o := &InstanceIPAddress{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, false); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress object: %s", err)
	}

	AddInstanceIPAddressHook(boil.BeforeInsertHook, instanceIPAddressBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressBeforeInsertHooks = []InstanceIPAddressHook{}

	AddInstanceIPAddressHook(boil.AfterInsertHook, instanceIPAddressAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressAfterInsertHooks = []InstanceIPAddressHook{}

	AddInstanceIPAddressHook(boil.AfterSelectHook, instanceIPAddressAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressAfterSelectHooks = []InstanceIPAddressHook{}

	AddInstanceIPAddressHook(boil.BeforeUpdateHook, instanceIPAddressBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressBeforeUpdateHooks = []InstanceIPAddressHook{}

	AddInstanceIPAddressHook(boil.AfterUpdateHook, instanceIPAddressAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressAfterUpdateHooks = []InstanceIPAddressHook{}

	AddInstanceIPAddressHook(boil.BeforeDeleteHook, instanceIPAddressBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressBeforeDeleteHooks = []InstanceIPAddressHook{}

	AddInstanceIPAddressHook(boil.AfterDeleteHook, instanceIPAddressAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressAfterDeleteHooks = []InstanceIPAddressHook{}

	AddInstanceIPAddressHook(boil.BeforeUpsertHook, instanceIPAddressBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressBeforeUpsertHooks = []InstanceIPAddressHook{}

	AddInstanceIPAddressHook(boil.AfterUpsertHook, instanceIPAddressAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	instanceIPAddressAfterUpsertHooks = []InstanceIPAddressHook{}
}

func testInstanceIPAddressesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testInstanceIPAddressesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(instanceIPAddressColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testInstanceIPAddressesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testInstanceIPAddressesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := InstanceIPAddressSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testInstanceIPAddressesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := InstanceIPAddresses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	instanceIPAddressDBTypes = map[string]string{`ID`: `uuid`, `InstanceID`: `uuid`, `Address`: `inet`, `CreatedAt`: `timestamptz`, `UpdatedAt`: `timestamptz`}
	_                        = bytes.MinRead
)

func testInstanceIPAddressesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(instanceIPAddressPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(instanceIPAddressAllColumns) == len(instanceIPAddressPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testInstanceIPAddressesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(instanceIPAddressAllColumns) == len(instanceIPAddressPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &InstanceIPAddress{}
	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := InstanceIPAddresses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, instanceIPAddressDBTypes, true, instanceIPAddressPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize InstanceIPAddress struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(instanceIPAddressAllColumns, instanceIPAddressPrimaryKeyColumns) {
		fields = instanceIPAddressAllColumns
	} else {
		fields = strmangle.SetComplement(
			instanceIPAddressAllColumns,
			instanceIPAddressPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := InstanceIPAddressSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}
