// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

func testMetadataUpsert(t *testing.T) {
	t.Parallel()

	if len(metadatumAllColumns) == len(metadatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Metadatum{}
	if err = randomize.Struct(seed, &o, metadatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Metadatum: %s", err)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, metadatumDBTypes, false, metadatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Metadatum: %s", err)
	}

	count, err = Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMetadata(t *testing.T) {
	t.Parallel()

	query := Metadata()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMetadataDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMetadataQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Metadata().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMetadataSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MetadatumSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMetadataExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MetadatumExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Metadatum exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MetadatumExists to return true, but got false.")
	}
}

func testMetadataFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	metadatumFound, err := FindMetadatum(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if metadatumFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMetadataBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Metadata().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMetadataOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Metadata().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMetadataAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	metadatumOne := &Metadatum{}
	metadatumTwo := &Metadatum{}
	if err = randomize.Struct(seed, metadatumOne, metadatumDBTypes, false, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}
	if err = randomize.Struct(seed, metadatumTwo, metadatumDBTypes, false, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = metadatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = metadatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Metadata().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMetadataCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	metadatumOne := &Metadatum{}
	metadatumTwo := &Metadatum{}
	if err = randomize.Struct(seed, metadatumOne, metadatumDBTypes, false, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}
	if err = randomize.Struct(seed, metadatumTwo, metadatumDBTypes, false, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = metadatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = metadatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func metadatumBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func metadatumAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func metadatumAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func metadatumBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func metadatumAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func metadatumBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func metadatumAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func metadatumBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func metadatumAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Metadatum) error {
	*o = Metadatum{}
	return nil
}

func testMetadataHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Metadatum{}
	o := &Metadatum{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, metadatumDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Metadatum object: %s", err)
	}

	AddMetadatumHook(boil.BeforeInsertHook, metadatumBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	metadatumBeforeInsertHooks = []MetadatumHook{}

	AddMetadatumHook(boil.AfterInsertHook, metadatumAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	metadatumAfterInsertHooks = []MetadatumHook{}

	AddMetadatumHook(boil.AfterSelectHook, metadatumAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	metadatumAfterSelectHooks = []MetadatumHook{}

	AddMetadatumHook(boil.BeforeUpdateHook, metadatumBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	metadatumBeforeUpdateHooks = []MetadatumHook{}

	AddMetadatumHook(boil.AfterUpdateHook, metadatumAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	metadatumAfterUpdateHooks = []MetadatumHook{}

	AddMetadatumHook(boil.BeforeDeleteHook, metadatumBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	metadatumBeforeDeleteHooks = []MetadatumHook{}

	AddMetadatumHook(boil.AfterDeleteHook, metadatumAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	metadatumAfterDeleteHooks = []MetadatumHook{}

	AddMetadatumHook(boil.BeforeUpsertHook, metadatumBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	metadatumBeforeUpsertHooks = []MetadatumHook{}

	AddMetadatumHook(boil.AfterUpsertHook, metadatumAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	metadatumAfterUpsertHooks = []MetadatumHook{}
}

func testMetadataInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMetadataInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(metadatumColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMetadataReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMetadataReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MetadatumSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMetadataSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Metadata().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	metadatumDBTypes = map[string]string{`ID`: `uuid`, `Metadata`: `jsonb`, `CreatedAt`: `timestamptz`, `UpdatedAt`: `timestamptz`}
	_                = bytes.MinRead
)

func testMetadataUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(metadatumPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(metadatumAllColumns) == len(metadatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMetadataSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(metadatumAllColumns) == len(metadatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Metadatum{}
	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Metadata().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, metadatumDBTypes, true, metadatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Metadatum struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(metadatumAllColumns, metadatumPrimaryKeyColumns) {
		fields = metadatumAllColumns
	} else {
		fields = strmangle.SetComplement(
			metadatumAllColumns,
			metadatumPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MetadatumSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}
